name: parent_progress
description: "This package offers a solution for managing and tracking progress across multiple tasks with three main classes: FictionalProgress, RationalProgress, and ParentProgress."
version: 0.2.2
homepage: https://clipspace.app/
repository: https://github.com/olerhan/parent_progress.git
issue_tracker: https://github.com/olerhan/parent_progress/issues
topics:
  - progress
  - indicator
  - tracking
  - management
  - manual

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0