name: parent_progress
description: "This package offers a solution for managing and tracking progress across multiple tasks with three main classes: FictionalProgress, RationalProgress, and ParentProgress. It allows each child progress to independently track and contribute to an aggregated parent progress, using ValueNotifier<int> for dynamic updates and UI integration. Ideal for complex progress management in modular applications."
version: 0.0.1
repository: https://github.com/olerhan/parent_progress.git
topics:
  - progress
  - indicator
  - tracking
  - management
  - manual

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0